### PR TITLE
Update golang version to 1.11

### PR DESCRIPTION
**Pull request by sspaink**
Updating golang version to 1.11 hoping to use new features (e.g. modules).

### CODE REVIEW

**Review by denismakogon — APPROVED** [review]
I will update images soon. Thanks.

**Comment by denismakogon** [comment]
My personal recommendation go switch to ffmpeg-debian (I also maintain them) for sake of stability and glibc compatibility.

**Comment by denismakogon** [comment]
@BattleBas tags were updated, but I created another tag: `4.0-golang-1.11` specifically for your demand.

**Comment by sspaink** [comment]
@denismakogon  thank you very much! 

Would it be possible to also update your gocv-alpine image on hub.docker.com ? I was hoping to use the updated ffmpeg image with it.

**Comment by denismakogon** [comment]
Yup,’gonna take care of that today.

**Pull request merged**
